name: BlastDT_daily_update

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone Weather Data Repository
      run: git clone --depth 1 https://github.com/Raingel/historical_weather.git weather_data
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: exec blast_predict_nian.py
      run: |
        python BLASTDT.py --RH_THRESHOLD 80 --T_THRESHOLD 23.5 --WINDOWS_LENGTH 1 --START_YEAR 2020 
    - name: Remove weather_data directory
      run: rm -rf weather_data
    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "BlastDT Risk Assessment results for $(date +'%Y-%m-%d')"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
